#include "portfolio/delivery/portfolio_capability_catalog.hpp"
#include <gtest/gtest.h>
#include <duckdb.hpp>
#include <filesystem>
#include <fstream>
#include <cstdlib>
namespace fs=std::filesystem;
namespace { std::string id="7359f9cf-c2e0-4a61-ab7b-a5fd0918cbbb", stream="4b809f2e-5606-4f45-b050-e4dbb30cde53";
std::string bytes(const fs::path&p){std::ifstream in(p,std::ios::binary);return {std::istreambuf_iterator<char>(in),{}};}
TEST(PortfolioCapabilityCatalog, SyncsRealReadOnlySourceAndSearchesMetadata){const auto base=fs::temp_directory_path()/"axon-g13-catalog";fs::remove_all(base);fs::create_directories(base/"repo/.axon");const auto source=base/"repo/.axon/index.duckdb";{duckdb::DuckDB db(source.string());duckdb::Connection c(db);ASSERT_FALSE(c.Query("CREATE TABLE index_metadata(singleton BOOLEAN,repository_id VARCHAR,index_stream_id VARCHAR,current_epoch VARCHAR,current_manifest VARCHAR)")->HasError());ASSERT_FALSE(c.Query("CREATE TABLE index_events(sequence UBIGINT)")->HasError());ASSERT_FALSE(c.Query("CREATE TABLE files(id BIGINT,path VARCHAR,language VARCHAR,hash VARCHAR)")->HasError());ASSERT_FALSE(c.Query("CREATE TABLE symbols(file_id BIGINT,name VARCHAR)")->HasError());ASSERT_FALSE(c.Query("CREATE TABLE routes(handler_file VARCHAR,method VARCHAR,path VARCHAR)")->HasError());ASSERT_FALSE(c.Query("INSERT INTO index_metadata VALUES(true,'"+id+"','"+stream+"','epoch-000000000001','manifest-000000000001')")->HasError());ASSERT_FALSE(c.Query("INSERT INTO index_events VALUES(1)")->HasError());ASSERT_FALSE(c.Query("INSERT INTO files VALUES(1,'src/payment.cpp','cpp','0123456789abcdef'),(2,'src/search.cpp','cpp','fedcba9876543210')")->HasError());ASSERT_FALSE(c.Query("INSERT INTO symbols VALUES(1,'authorize'),(2,'query')")->HasError());ASSERT_FALSE(c.Query("INSERT INTO routes VALUES('src/payment.cpp','POST','/pay')")->HasError());}const auto before=bytes(source);fs::create_directories(base/"registry");std::ofstream(base/"registry/registry.json")<<"{\"schema_version\":\"axon-registry/v2\",\"repos\":[{\"name\":\"repo\",\"root\":\""<<(base/"repo").string()<<"\",\"db_path\":\""<<source.string()<<"\",\"repository_id\":\""<<id<<"\",\"index_stream_id\":\""<<stream<<"\",\"default_for_profiles\":[\"local\"]}],\"storage_profiles\":{\"local\":{\"role\":\"portfolio_local\",\"transport\":\"local\",\"default\":true,\"portfolio_store\":{\"provider\":\"duckdb\",\"path\":\"x\"}}}}";setenv("AXON_REGISTRY_DIR",(base/"registry").c_str(),1);axon::portfolio::PortfolioCapabilityCatalog catalog(base/"catalog.duckdb");const auto report=catalog.sync();ASSERT_FALSE(report.degraded);ASSERT_EQ(report.repositories[0].signatures,2u);EXPECT_EQ(bytes(source),before);EXPECT_EQ(catalog.search("payment").size(),1u);EXPECT_EQ(catalog.list({},10).size(),2u);}
}
