#pragma once

#include <string>

namespace axon::portfolio::web {

// Dependency-free and local-first: this page never persists a token or loads remote assets.
inline std::string page() {
    return R"AXONHTML(<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Axon capability atlas</title></head><body><main>
<h1>Capability atlas</h1><p id="help">Explore a bounded, read-only projection. A token is held only in this page session.</p>
<label for="t">Keycloak access token</label><input id="t" type="password" autocomplete="off" aria-describedby="help" placeholder="Keycloak access token (session only)"><button id="go" type="button">Inspect portfolio</button><output id="state" aria-live="polite">Not connected</output>
<section aria-labelledby="topology-title"><h2 id="topology-title">Topology</h2><p id="topology-note"></p><div id="top" aria-label="Capability topology"></div></section>
<section aria-labelledby="connections-title"><h2 id="connections-title">Connections / compare</h2><div id="edges" aria-label="Capability convergence candidates"></div></section>
<section aria-labelledby="evidence-title"><h2 id="evidence-title">Evidence / consumers / packages</h2><div id="detail" tabindex="-1">Select a capability.</div></section>
<section aria-labelledby="drift-title"><h2 id="drift-title">Declared capability drift</h2><label for="graph-root">Registered graph root</label><input id="graph-root" autocomplete="off" placeholder="Registered repository root"><label for="fragment">Declaration fragment</label><input id="fragment" autocomplete="off" placeholder="Relative Git fragment path"><button id="drift" type="button">Check declaration drift</button></section>
</main><script>
const $=x=>document.getElementById(x),limit=100;function clear(id){$(id).replaceChildren()}function text(parent,value){parent.append(document.createTextNode(value))}function button(parent,label,action){let b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',action);parent.append(b)}
async function api(path,allowDegraded=false){let response=await fetch(path,{headers:{Authorization:'Bearer '+$('t').value}});let body=await response.json();if(!response.ok&&!(allowDegraded&&response.status===503))throw Error(body.error||String(response.status));return body}function focusDetail(){$('detail').focus()}
async function node(capability){try{let consumers=await api('/api/v1/capabilities/consumers/'+encodeURIComponent(capability.id));clear('detail');text($('detail'),'Repository: '+capability.repository_id+' | Path: '+capability.path+' | Epoch: '+capability.epoch+' | Contracts: '+(capability.contracts||[]).join(', ')+' | Routes: '+(capability.routes||[]).join(', ')+' | Observed local consumers: '+(consumers.consumer_capabilities||[]).join(', ')+' | Unresolved import specifiers (may include packages): '+(consumers.unresolved_import_specifiers||[]).join(', ')+' | Evidence: '+(consumers.evidence||[]).join(', '));focusDetail()}catch(error){$('state').textContent='Capability detail unavailable: '+error.message}}
async function compare(candidate){try{let result=await api('/api/v1/capabilities/compare/'+encodeURIComponent(candidate.id));clear('detail');text($('detail'),'Comparison '+result.classification+' score '+result.score+' | Differences: '+(result.differences||[]).join(', ')+' | Invalidators: '+(result.invalidators||[]).join(', '));focusDetail()}catch(error){$('state').textContent='Comparison unavailable: '+error.message}}
async function drift(){try{let root=$('graph-root').value,fragment=$('fragment').value;if(!root||!fragment)throw Error('registered graph root and fragment are required');let result=await api('/api/v1/capabilities/drift?graph_root='+encodeURIComponent(root)+'&fragment='+encodeURIComponent(fragment));clear('detail');text($('detail'),'Declared matches: '+result.matches+' | Observed/declaration drift: '+result.drift);focusDetail()}catch(error){$('state').textContent='Drift unavailable: '+error.message}}
async function load(){try{let [status,topology]=await Promise.all([api('/api/v1/portfolio/status',true),api('/api/v1/portfolio/topology?limit='+limit)]);$('state').textContent=status.degraded?'Degraded: some sources are stale':'Fresh';$('topology-note').textContent=topology.truncated?'Showing the first '+limit+' capabilities; refine through the API for more.':'Showing '+(topology.nodes||[]).length+' capabilities.';clear('top');for(const capability of (topology.nodes||[]))button($('top'),capability.name+' — '+capability.repository_id,()=>node(capability));clear('edges');if(!(topology.edges||[]).length)text($('edges'),'No convergence edges');for(const candidate of (topology.edges||[]))button($('edges'),candidate.classification+' '+Math.round(candidate.score*100)+'%',()=>compare(candidate))}catch(error){$('state').textContent='Unavailable: '+error.message}}
$('go').addEventListener('click',load);$('drift').addEventListener('click',drift);
</script><style>body{background:#101722;color:#e8edf5;font:16px system-ui,sans-serif;margin:0}main{max-width:70rem;margin:auto;padding:2rem}section{border-top:1px solid #38485c;margin-top:1.5rem;padding-top:1rem}input{display:block;box-sizing:border-box;margin:.35rem 0 1rem;max-width:44rem;width:100%}button{background:#1e3651;border:1px solid #7187a1;border-radius:.25rem;color:inherit;margin:.25rem;padding:.45rem .65rem}button:focus-visible,input:focus-visible{outline:3px solid #f5b942;outline-offset:2px}output{display:block;min-height:1.4rem}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}</style></body></html>)AXONHTML";
}

} // namespace axon::portfolio::web
