#include "capability_candidates.hpp"

#include <algorithm>
#include <cmath>
#include <set>
#include <stdexcept>
#include <tuple>
#include <utility>

namespace axon::portfolio {
namespace {
using StringSet = std::set<std::string>;
struct PairKey { std::string left, right; bool operator<(const PairKey& other) const { return std::tie(left, right) < std::tie(other.left, other.right); } };
struct PairData { const CapabilitySignature* left = nullptr; const CapabilitySignature* right = nullptr; std::map<CandidateSignal, double> raw; std::map<CandidateSignal, std::size_t> ranks; };

std::map<CandidateSignal, double> default_weights() { return {{CandidateSignal::semantic,1.0},{CandidateSignal::name,.8},{CandidateSignal::contracts,1.4},{CandidateSignal::endpoints,1.2},{CandidateSignal::events,1.0},{CandidateSignal::structure,1.4},{CandidateSignal::dependencies,.8},{CandidateSignal::graph_neighborhood,.7},{CandidateSignal::tests,.7}}; }
StringSet set_of(const std::vector<std::string>& values) { return {values.begin(), values.end()}; }
StringSet merge(std::initializer_list<StringSet> all) { StringSet result; for (const auto& values : all) result.insert(values.begin(), values.end()); return result; }
StringSet name_tokens(const std::string& value) { StringSet result; std::string token; for (char c : value) { if (c == ' ') { if (!token.empty()) { result.insert(token); token.clear(); } } else token += c; } if (!token.empty()) result.insert(token); return result; }
StringSet neighbors(const CapabilitySignature& signature) { StringSet result; for (const auto& n : signature.call_graph_neighborhood) { result.insert(n.direction + ":" + n.relation + ":" + n.entity_key); if (n.digest) result.insert("digest:" + *n.digest); } return result; }
double jaccard(const StringSet& left, const StringSet& right) { if (left.empty() || right.empty()) return 0.0; std::size_t intersect = 0; for (const auto& item : left) intersect += right.contains(item) ? 1 : 0; return static_cast<double>(intersect) / static_cast<double>(left.size() + right.size() - intersect); }
double get(const std::map<CandidateSignal,double>& values, CandidateSignal signal) { const auto it=values.find(signal); return it == values.end() ? 0.0 : it->second; }
bool context_mismatch(const CapabilitySignature& l, const CapabilitySignature& r) { return l.bounded_context && r.bounded_context && *l.bounded_context != *r.bounded_context; }
PairKey key_for(const CapabilitySignature& first, const CapabilitySignature& second) { auto left=capability_reference_id(first); auto right=capability_reference_id(second); if (right < left) std::swap(left,right); return {std::move(left),std::move(right)}; }
bool positive(const PairData& pair) { return std::any_of(pair.raw.begin(),pair.raw.end(),[](const auto& score){ return score.first != CandidateSignal::domain_context && score.second > 0.0; }); }
void validate(const CandidateGenerationConfig& config) { if (config.rrf_k==0 || config.rrf_k>1000 || config.max_signatures==0 || config.max_signatures>10000 || config.max_candidates_per_capability==0 || config.max_candidates_per_capability>1000 || config.max_candidates==0 || config.max_candidates>100000) throw std::invalid_argument("invalid candidate generation bounds"); for (const auto& [signal,weight] : config.weights) if (signal==CandidateSignal::domain_context || !std::isfinite(weight) || weight<=0 || weight>10) throw std::invalid_argument("invalid candidate signal weight"); }
std::vector<std::string> shared(const StringSet& left,const StringSet& right,const std::string& prefix) { std::vector<std::string> result; for(const auto& value:left) if(right.contains(value)) { result.push_back(prefix+":"+value); if(result.size()==5) break; } return result; }
} // namespace

const char* to_string(CandidateSignal signal) { switch(signal) { case CandidateSignal::semantic:return "semantic"; case CandidateSignal::name:return "name"; case CandidateSignal::contracts:return "contracts"; case CandidateSignal::endpoints:return "endpoints"; case CandidateSignal::events:return "events"; case CandidateSignal::structure:return "structure"; case CandidateSignal::dependencies:return "dependencies"; case CandidateSignal::graph_neighborhood:return "graph_neighborhood"; case CandidateSignal::tests:return "tests"; case CandidateSignal::domain_context:return "domain_context"; } return "unknown"; }
const char* to_string(CapabilityClassification value) { switch(value) { case CapabilityClassification::exact_duplicate:return "exact_duplicate"; case CapabilityClassification::convergent_capability:return "convergent_capability"; case CapabilityClassification::shared_primitive_candidate:return "shared_primitive_candidate"; case CapabilityClassification::local_specialization:return "local_specialization"; case CapabilityClassification::semantic_coincidence:return "semantic_coincidence"; case CapabilityClassification::insufficient_evidence:return "insufficient_evidence"; } return "insufficient_evidence"; }
const char* to_string(CapabilityRecommendation value) { switch(value) { case CapabilityRecommendation::consolidation_review:return "consolidation_review"; case CapabilityRecommendation::extract_shared_primitive:return "extract_shared_primitive"; case CapabilityRecommendation::keep_local:return "keep_local"; case CapabilityRecommendation::collect_more_evidence:return "collect_more_evidence"; } return "collect_more_evidence"; }
std::string capability_reference_id(const CapabilitySignature& value) { if(value.stream.repository_id.empty()||value.stream.index_stream_id.empty()||value.signature_id.empty()) throw std::invalid_argument("capability reference identity is required"); return value.stream.repository_id+":"+value.stream.index_stream_id+":"+value.signature_id; }

CapabilityCandidateGenerator::CapabilityCandidateGenerator(CandidateGenerationConfig config):config_(std::move(config)) { if(config_.weights.empty()) config_.weights=default_weights(); validate(config_); }
std::vector<CapabilityCandidate> CapabilityCandidateGenerator::generate(const std::vector<CapabilitySignature>& signatures,const std::vector<SemanticCandidateHint>& hints) const {
    if(signatures.size()>config_.max_signatures) throw std::invalid_argument("candidate signature input exceeds configured bound");
    std::map<std::string,const CapabilitySignature*> refs;
    for(const auto& signature:signatures) if(!refs.emplace(capability_reference_id(signature),&signature).second) throw std::invalid_argument("duplicate capability reference");
    std::map<PairKey,PairData> pairs;
    for(std::size_t i=0;i<signatures.size();++i) for(std::size_t j=i+1;j<signatures.size();++j) {
        const auto& left=signatures[i]; const auto& right=signatures[j]; if(left.stream.repository_id==right.stream.repository_id) continue;
        const auto key=key_for(left,right); auto& pair=pairs[key]; pair.left=refs.at(key.left); pair.right=refs.at(key.right);
        pair.raw[CandidateSignal::name]=jaccard(name_tokens(left.normalized_name),name_tokens(right.normalized_name));
        pair.raw[CandidateSignal::contracts]=jaccard(merge({set_of(left.public_symbols),set_of(left.contracts),set_of(left.schemas),set_of(left.dtos)}),merge({set_of(right.public_symbols),set_of(right.contracts),set_of(right.schemas),set_of(right.dtos)}));
        pair.raw[CandidateSignal::endpoints]=jaccard(merge({set_of(left.routes),set_of(left.handlers)}),merge({set_of(right.routes),set_of(right.handlers)}));
        pair.raw[CandidateSignal::events]=jaccard(set_of(left.events),set_of(right.events));
        pair.raw[CandidateSignal::structure]=jaccard(set_of(left.ast_fingerprints),set_of(right.ast_fingerprints));
        pair.raw[CandidateSignal::dependencies]=jaccard(merge({set_of(left.internal_dependencies),set_of(left.external_dependencies)}),merge({set_of(right.internal_dependencies),set_of(right.external_dependencies)}));
        pair.raw[CandidateSignal::graph_neighborhood]=jaccard(neighbors(left),neighbors(right));
        pair.raw[CandidateSignal::tests]=jaccard(set_of(left.tests),set_of(right.tests));
        pair.raw[CandidateSignal::domain_context]=context_mismatch(left,right)?-1.0:(left.bounded_context&&right.bounded_context?1.0:0.0);
    }
    for(const auto& hint:hints) {
        if(!std::isfinite(hint.score)||hint.score<0||hint.score>1||!refs.contains(hint.left_capability_id)||!refs.contains(hint.right_capability_id)||hint.left_capability_id==hint.right_capability_id) throw std::invalid_argument("invalid semantic candidate hint");
        const auto* left=refs.at(hint.left_capability_id); const auto* right=refs.at(hint.right_capability_id); if(left->stream.repository_id==right->stream.repository_id) continue;
        const auto key=key_for(*left,*right); auto& pair=pairs[key]; pair.left=refs.at(key.left); pair.right=refs.at(key.right); pair.raw[CandidateSignal::semantic]=std::max(get(pair.raw,CandidateSignal::semantic),hint.score); if(!pair.raw.contains(CandidateSignal::domain_context)) pair.raw[CandidateSignal::domain_context]=context_mismatch(*pair.left,*pair.right)?-1.0:(pair.left->bounded_context&&pair.right->bounded_context?1.0:0.0);
    }
    for(const auto& [reference,source]:refs) { (void)source; for(const auto& [signal,weight]:config_.weights) { (void)weight; std::vector<std::pair<PairKey,double>> ranked; for(const auto& [key,pair]:pairs) if((key.left==reference||key.right==reference)&&get(pair.raw,signal)>0) ranked.emplace_back(key,get(pair.raw,signal)); std::sort(ranked.begin(),ranked.end(),[](const auto& a,const auto& b){return a.second!=b.second?a.second>b.second:a.first<b.first;}); for(std::size_t i=0;i<std::min(ranked.size(),config_.max_candidates_per_capability);++i) { auto& rank=pairs.at(ranked[i].first).ranks[signal]; if(rank==0||i+1<rank) rank=i+1; } } }
    std::vector<CapabilityCandidate> result;
    for(const auto& [key,pair]:pairs) {
        if(!positive(pair)||pair.ranks.empty()) continue;
        CapabilityCandidate item; item.candidate_id=key.left+"|"+key.right; item.left_capability_id=key.left; item.right_capability_id=key.right; item.left_repository_id=pair.left->stream.repository_id; item.right_repository_id=pair.right->stream.repository_id; item.left_index_epoch=pair.left->index_epoch; item.right_index_epoch=pair.right->index_epoch;
        double numerator=0,denominator=0,raw_total=0; std::size_t positives=0;
        for(const auto& [signal,weight]:config_.weights) { const auto raw=get(pair.raw,signal); const auto found=pair.ranks.find(signal); const auto rank=found==pair.ranks.end()?0:found->second; const auto fused=rank==0?0:weight/static_cast<double>(config_.rrf_k+rank); if(raw>0){++positives;raw_total+=raw;} numerator+=fused;denominator+=weight/static_cast<double>(config_.rrf_k+1); item.signals.push_back({signal,raw,rank,fused,raw>0?std::vector<std::string>{std::string(to_string(signal))+" score="+std::to_string(raw)}:std::vector<std::string>{}}); }
        const bool mismatch=get(pair.raw,CandidateSignal::domain_context)<0; item.signals.push_back({CandidateSignal::domain_context,get(pair.raw,CandidateSignal::domain_context),0,0,{mismatch?"bounded_context differs":"bounded_context compatible or absent"}}); item.final_score=denominator==0?0:numerator/denominator; item.confidence=std::clamp(.10*static_cast<double>(positives)+.45*(raw_total/static_cast<double>(positives))+.45*item.final_score,0.0,1.0);
        const auto left_contracts=merge({set_of(pair.left->public_symbols),set_of(pair.left->contracts),set_of(pair.left->schemas),set_of(pair.left->dtos)}); const auto right_contracts=merge({set_of(pair.right->public_symbols),set_of(pair.right->contracts),set_of(pair.right->schemas),set_of(pair.right->dtos)}); for(auto evidence:shared(left_contracts,right_contracts,"contract")) item.matching_references.push_back(std::move(evidence)); for(auto evidence:shared(set_of(pair.left->ast_fingerprints),set_of(pair.right->ast_fingerprints),"ast")) item.matching_references.push_back(std::move(evidence));
        if(pair.left->bounded_context!=pair.right->bounded_context)item.differences.push_back("bounded_context differs"); if(pair.left->normalized_name!=pair.right->normalized_name)item.differences.push_back("normalized names differ"); if(left_contracts!=right_contracts)item.differences.push_back("contracts differ"); if(pair.left->routes!=pair.right->routes)item.differences.push_back("routes differ"); if(pair.left->handlers!=pair.right->handlers)item.differences.push_back("handlers differ"); if(pair.left->events!=pair.right->events)item.differences.push_back("events differ"); if(set_of(pair.left->ast_fingerprints)!=set_of(pair.right->ast_fingerprints))item.differences.push_back("structural fingerprints differ"); if(merge({set_of(pair.left->internal_dependencies),set_of(pair.left->external_dependencies)})!=merge({set_of(pair.right->internal_dependencies),set_of(pair.right->external_dependencies)}))item.differences.push_back("dependencies differ"); if(neighbors(*pair.left)!=neighbors(*pair.right))item.differences.push_back("graph neighborhood differs"); if(set_of(pair.left->tests)!=set_of(pair.right->tests))item.differences.push_back("tests differ"); if(pair.left->index_epoch!=pair.right->index_epoch)item.differences.push_back("freshness epochs differ"); if(mismatch){item.invalidators.push_back("bounded_context mismatch prevents duplicate promotion");item.confidence=std::min(item.confidence,.25);} if(positives<2){item.invalidators.push_back("fewer than two independent positive signals");item.confidence=std::min(item.confidence,.40);} if(item.matching_references.empty())item.invalidators.push_back("no contract or structural correspondence");
        const auto name=get(pair.raw,CandidateSignal::name), contracts=get(pair.raw,CandidateSignal::contracts), structure=get(pair.raw,CandidateSignal::structure), endpoints=get(pair.raw,CandidateSignal::endpoints), semantic=get(pair.raw,CandidateSignal::semantic); const bool implementation_difference=pair.left->routes!=pair.right->routes||pair.left->handlers!=pair.right->handlers||pair.left->events!=pair.right->events; if(mismatch&&(name>0||semantic>0)){item.classification=CapabilityClassification::semantic_coincidence;item.recommendation=CapabilityRecommendation::keep_local;} else if(positives>=3&&name>=.8&&contracts>=.9&&structure>=.9&&!implementation_difference){item.classification=CapabilityClassification::exact_duplicate;item.recommendation=CapabilityRecommendation::consolidation_review;} else if(positives>=2&&(contracts>=.4||structure>=.4)&&implementation_difference){item.classification=CapabilityClassification::local_specialization;item.recommendation=CapabilityRecommendation::keep_local;} else if(positives>=3&&(contracts>=.5||endpoints>=.5)&&(semantic>=.4||name>=.5||structure>=.5)){item.classification=CapabilityClassification::convergent_capability;item.recommendation=CapabilityRecommendation::consolidation_review;} else if(positives>=3&&(contracts>=.4||endpoints>=.4)&&item.final_score>=.20){item.classification=CapabilityClassification::shared_primitive_candidate;item.recommendation=CapabilityRecommendation::extract_shared_primitive;} else {item.classification=CapabilityClassification::insufficient_evidence;item.recommendation=CapabilityRecommendation::collect_more_evidence;} result.push_back(std::move(item));
    }
    std::sort(result.begin(),result.end(),[](const auto& a,const auto& b){return a.final_score!=b.final_score?a.final_score>b.final_score:a.candidate_id<b.candidate_id;}); std::map<std::string,std::size_t> final_fanout; std::vector<CapabilityCandidate> bounded; for(auto& candidate:result) { if(final_fanout[candidate.left_capability_id]>=config_.max_candidates_per_capability||final_fanout[candidate.right_capability_id]>=config_.max_candidates_per_capability) continue; ++final_fanout[candidate.left_capability_id]; ++final_fanout[candidate.right_capability_id]; bounded.push_back(std::move(candidate)); if(bounded.size()==config_.max_candidates) break; } return bounded;
}
} // namespace axon::portfolio
