#include "pgvector_semantic_store.hpp"
#include <algorithm>
#include <cmath>
#include <cctype>
#include <sstream>
#include <stdexcept>

namespace axon::portfolio { namespace {
std::string vector_text(const std::vector<float>& values) { std::ostringstream out; out << '['; for (std::size_t i=0;i<values.size();++i) { if(i) out << ','; out << values[i]; } return out << ']', out.str(); }
void command(PGconn* c, const std::string& sql) { PGresult* r=PQexec(c,sql.c_str()); if(!r || PQresultStatus(r)!=PGRES_COMMAND_OK) { if(r) PQclear(r); throw std::runtime_error("pgvector command failed"); } PQclear(r); }
PGresult* query(PGconn* c,const char* sql,const std::vector<std::string>& p) { std::vector<const char*> v; for(auto& x:p)v.push_back(x.c_str()); PGresult* r=PQexecParams(c,sql,v.size(),nullptr,v.data(),nullptr,nullptr,0); if(!r || PQresultStatus(r)!=PGRES_TUPLES_OK) {if(r)PQclear(r); throw std::runtime_error("pgvector query failed");} return r; }
bool identifier(const std::string& value) { return !value.empty() && std::all_of(value.begin(), value.end(), [](unsigned char c) { return std::isalnum(c) || c == '_'; }); }
}
PgvectorSemanticStore::PgvectorSemanticStore(std::string dsn,std::uint32_t dimension,std::string table_name):dimension_(dimension),table_name_(std::move(table_name)),connection_(PQconnectdb(dsn.c_str())) { if(!connection_||PQstatus(connection_)!=CONNECTION_OK||!dimension_||dimension_>65536||!identifier(table_name_)) throw std::runtime_error("pgvector unavailable"); migrate(); }
PgvectorSemanticStore::~PgvectorSemanticStore(){ if(connection_)PQfinish(connection_); }
void PgvectorSemanticStore::migrate(){ std::lock_guard lock(mutex_); command(connection_,"BEGIN"); try { auto advisory=query(connection_,"SELECT pg_advisory_xact_lock(hashtext('axon_portfolio_pgvector_migration'))",{}); PQclear(advisory); command(connection_,"CREATE EXTENSION IF NOT EXISTS vector"); command(connection_,"CREATE TABLE IF NOT EXISTS "+table_name_+" (signature_id text NOT NULL, repository_id uuid NOT NULL, index_epoch text NOT NULL, model_id text NOT NULL, dimension integer NOT NULL, metric text NOT NULL, generation text NOT NULL, embedding vector("+std::to_string(dimension_)+") NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(signature_id,generation,model_id))"); auto result=query(connection_,("SELECT atttypmod FROM pg_attribute WHERE attrelid='"+table_name_+"'::regclass AND attname='embedding'").c_str(),{}); if(PQntuples(result)!=1 || std::stoul(PQgetvalue(result,0,0))!=dimension_) { PQclear(result); throw std::runtime_error("pgvector dimension schema mismatch"); } PQclear(result); const auto pk_sql="SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid='"+table_name_+"'::regclass AND contype='p'"; result=query(connection_,pk_sql.c_str(),{}); const bool compatible=PQntuples(result)==1 && std::string(PQgetvalue(result,0,0)).find("signature_id, generation, model_id")!=std::string::npos; PQclear(result); if(!compatible) { command(connection_,"ALTER TABLE "+table_name_+" DROP CONSTRAINT IF EXISTS "+table_name_+"_pkey"); command(connection_,"ALTER TABLE "+table_name_+" ADD PRIMARY KEY(signature_id,generation,model_id)"); } command(connection_,"COMMIT"); } catch (...) { PGresult* rollback=PQexec(connection_,"ROLLBACK"); if(rollback) PQclear(rollback); throw; } }
void PgvectorSemanticStore::upsert(const SemanticRecord& r){ validate_semantic_identity(r.identity,r.vector); if(r.identity.dimension!=dimension_||r.signature_id.empty()||r.repository_id.empty()||r.index_epoch.empty()) throw std::invalid_argument("semantic record identity mismatch"); std::lock_guard lock(mutex_); const auto sql="INSERT INTO "+table_name_+"(signature_id,repository_id,index_epoch,model_id,dimension,metric,generation,embedding) VALUES($1,$2,$3,$4,$5,$6,$7,$8::vector) ON CONFLICT(signature_id,generation,model_id) DO UPDATE SET repository_id=EXCLUDED.repository_id,index_epoch=EXCLUDED.index_epoch,dimension=EXCLUDED.dimension,metric=EXCLUDED.metric,embedding=EXCLUDED.embedding,updated_at=now() RETURNING signature_id"; PGresult* q=query(connection_,sql.c_str(),{r.signature_id,r.repository_id,r.index_epoch,r.identity.model_id,std::to_string(r.identity.dimension),r.identity.metric,r.identity.generation,vector_text(r.vector)}); PQclear(q); }
void PgvectorSemanticStore::erase(const std::string& id,const std::string& gen){std::lock_guard lock(mutex_); const auto sql="DELETE FROM "+table_name_+" WHERE signature_id=$1 AND generation=$2 RETURNING signature_id"; PGresult* q=query(connection_,sql.c_str(),{id,gen});PQclear(q);}
std::vector<SemanticHit> PgvectorSemanticStore::search(const std::vector<float>& v,const SemanticIdentity& i,std::size_t limit)const{validate_semantic_identity(i,v);if(i.dimension!=dimension_||limit==0||limit>200)throw std::invalid_argument("semantic search bounds");std::lock_guard lock(mutex_);const auto sql="SELECT signature_id, 1-(embedding <=> $1::vector) FROM "+table_name_+" WHERE model_id=$2 AND dimension=$3 AND metric=$4 AND generation=$5 ORDER BY embedding <=> $1::vector,signature_id LIMIT $6";PGresult* q=query(connection_,sql.c_str(),{vector_text(v),i.model_id,std::to_string(i.dimension),i.metric,i.generation,std::to_string(limit)});std::vector<SemanticHit> out;for(int n=0;n<PQntuples(q);++n)out.push_back({PQgetvalue(q,n,0),std::stof(PQgetvalue(q,n,1))});PQclear(q);return out;}
} // namespace axon::portfolio
